### ISSUE TITLE
Latest beats library breaks compliation

### ISSUE THREAD

**Issue by dlip** [aidan-/cloudtrailbeat#1]
When building fresh it uses the latest beats library which is not compatible resulting in the error

```
code/go/src/github.com/aidan-/cloudtrailbeat/beater/ctbeat.go:181: b.Events undefined (type *beat.Beat has no field or method Events)
```

A temporary fix is to lock the beats version in glide.yml

```
- package: github.com/elastic/beats
  version: a0f543d88691f3081d63fcce83defc57a631cb8c
```

**Comment by aidan-** [comment]
Eek, that doesn't look good at all.  Thanks for noticing the issue and reporting it!

I'll commit the temporary fix now and start looking at what changes will need to be made to use the newest libbeat.
