### ISSUE TITLE
Fails to enumerate folders from multi-region

### ISSUE THREAD

**Issue by andrewkrug** [aidan-/cloudtrailbeat#4]
Seems to fail at backfill in my case where I have a lot of regions.  No specific error.  Process completes and never imports.

2016/10/02 20:21:32.251119 publish.go:287: INFO Publisher name: kali
2016/10/02 20:21:32.251540 async.go:68: INFO Flush Interval set to: 1s
2016/10/02 20:21:32.251558 async.go:69: INFO Max Bulk Size set to: 50
2016/10/02 20:21:32.251573 async.go:77: DBG  create bulk processing worker (interval=1s, bulk size=50)
2016/10/02 20:21:32.251788 beat.go:256: INFO cloudtrailbeat start running.
2016/10/02 20:21:32.251810 ctbeat.go:188: INFO Running in backfill mode
2016/10/02 20:21:32.251824 ctbeat.go:247: INFO Backfilling using S3 bucket: s3://threatresponse-cloudtrail/
2016/10/02 20:22:13.266870 beat.go:264: INFO cloudtrailbeat cleanup

**Comment by aidan-** [comment]
I've just committed some minor changes that add some logging that may help determine what is going wrong.  Could you please pull the latest changes and test again using debug mode?  This should give a but more information on what is going on.

Here is an example with the required flags to run in debug:
`./cloudtrailbeat -e -v -d "*" -c <configfile.yml> -b <bucket-name-containing-logs> -p <path/to/logs/in/s3/bucket>`

Is your S3 bucket used only for CloudTrail logs, or are there other objects in there as well?  Have these logs been processed or are they raw from CloudTrail?  Do the files you're expecting to be added to the backlog queue end in `.json.gz` or something else?

**Comment by andrewkrug** [comment]
I tested this and had no further issues.  Can you reach out by e-mail though?  I'm working on another project and would love to chat with you about building a beat for Netflix EDDA.

**Comment by aidan-** [comment]
That's good to hear.  Currently the code doesn't loop through all of the results in a backfill, so if you have a lot of files (>100) you will need to use the `-p` flag to limit the search to individual sub folders.  If there is demand I will add the looping functionality, but for my use cases I've always needed to be quite specific about which days I am backfilling.

You can find my contact information using the link on my github profile, though I don't know how useful I will be.  I mostly just read the documentation on the [elastic website](https://www.elastic.co/guide/en/beats/libbeat/5.x/new-beat.html).
